# Generated by Django 4.1 on 2023-10-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_students_courses2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='courses',
        ),
    ]
