# Generated by Django 4.1 on 2023-10-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_remove_students_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('sid', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=64)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='myapp1.course')),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
