# Generated by Django 4.1 on 2023-10-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_student_delete_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='students',
        ),
    ]
